### ISSUE TITLE
fabric-sdk-node

### ISSUE THREAD

**Issue by KHYehor** [davidkhala/fabric-sdk-node#2]
Sorry, 狼哥. I didn't know how to contact you, so you chose this way.
Could you please give me your mail to concat, I have some questions to you about [fabric-sdk-node](https://github.com/hyperledger/fabric-sdk-node/blob/v1.4.17/test/integration/configtxlator.js).
Looking forward hearing from you,
Yehor.

**Comment by davidkhala** [comment]
@KHYehor since I have tranfered your issue to a right place, I think to discuss at here is good option
> Could you help with fabric-sdk (https://github.com/hyperledger/fabric-sdk-node/blob/v1.4.17/test/integration/configtxlator.js)  I mean this test case, where you update configuration of network with sdk avoid using shell commands, I am failing with it, I got messages like signatures needed but I have already signed it. 

For your question I think you choose a wrong identity to sign the transaction, due to fabric's strong access control design, the signature identity you need for some operation differs. Somecase you need orderer org admin, peer org admin and even multiple signature

**Comment by KHYehor** [comment]
Yes, (I am talking about test network) I have used org1 admin and org2
admin, I *didn't understand how to get crt+pem of Orderer admin*, I mean
where are they placed.

By the way, I have created this config_updated and signed it inside of
docker container - then tried to update it outside with sdk and got this -
what you are talking about.




*{  status: 'FORBIDDEN',  info: "config update for existing channel
did not pass initial checks: implicit policy evaluation failed - 0
sub-policies were satisfied, but this policy requires 1 of the
'Writers' sub-policies to be satisfied: permission denied"}*

But, when I am creating this config_update with sdk, and then trying
to update with sdk - I am getting this.




*{  status: 'BAD_REQUEST',  info: "could not determine channel ID:
error unmarshaling Payload: proto: can't skip unknown wire type 6"}*


чт, 18 февр. 2021 г. в 16:54, David Liu <notifications@github.com>:

**Comment by davidkhala** [comment]
Order Admin cert is put in your <crypto-material-root-path>/ordererOrganizations/<order-org-name>/users/...

**Comment by KHYehor** [comment]
Sorry sir for not answering to you,

Can we update channel configuration out of network if we have certificates
of enrolled admin?

It seems strange using an order for this, it breaks all security ideas when
everyone needs to have the order cert for updating.

пт, 19 февр. 2021 г. в 14:23, David Liu <notifications@github.com>:

**Comment by davidkhala** [comment]
@KHYehor Since it can be expanded into complex topic so I think keep it in short here is better. 
Some channel configuration is controlled by orderer admin, such as modify consortium, orderer address. 
Some channel configuration is controled by co-work peer admin (multiple signatures are required), such as add and remove organization
Some channel configuration is controlled by a single peer admin, such as rotating admin cert, tls ca cert within admin's own organization. 

Update channel is in anyway validated according to access control policy, which is implemented by verify signature by certificates to identify authorized signer. 

So for you case you have to figure out which policy is controlling your desired change, and fulfilling this by collection of signatures.

**Comment by KHYehor** [comment]
Thanks for your time and answers, have a nice day and good luck.

чт, 25 февр. 2021 г. в 05:32, David Liu <notifications@github.com>:
